### ISSUE TITLE
Failed to sync gradle

### ISSUE THREAD

**Issue by patian** [Kylentt/MediaPlayer2#1]
Failed to sync gradle when app first sync after open it in androdi studio.

Cause: couldn't find keystore.properties in root project 'MediaPlayer'

![error](https://user-images.githubusercontent.com/2491361/174089822-f2992841-aa42-4860-a984-4f1718deacdf.png)

**Comment by Psiae** [comment]
[removed signingConfigs block](https://github.com/flammky/MediaPlayer2/commit/b6a4f8b6598ceec354d3f888e7f0336c97838785)
